version: "2"

linters:
  default: none
  enable:
    - misspell
    - staticcheck
    - govet
    - revive
    - ineffassign
    - unused
    - unparam
    - prealloc
    - unconvert

  settings:
    staticcheck:
      checks: ["all", "-SA1019", "-ST1000", "-ST1003", "-QF1008"]

    revive:
      rules:
      - name: var-naming
        disabled: true
      
    misspell:
      locale: US

formatters:
  enable:
    - gofumpt
    - goimports
